objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Site__c.object
<CustomObject>
    <description>Digital list of OEMs belonging to each account.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>LMA Account No</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites</relationshipLabel>
        <relationshipName>Business_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites (LMA Account)</relationshipLabel>
        <relationshipName>Business_Sites1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Business Site</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Business Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CB_LMA_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Site_Type__c</field>
                <operation>notEqual</operation>
                <value>a0I40000007012Y</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LMA Relationship (Dealer Account)</relationshipLabel>
        <relationshipName>LMA_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Site_Type__r.Name</field>
                <operation>equals</operation>
                <value>Local Marketing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LMA Related Accounts</relationshipLabel>
        <relationshipName>LMA_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LMA Relationships</label>
    <nameField>
        <displayFormat>LMAR-{0000}</displayFormat>
        <label>LMA Relationships Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ALL_BusinessSites_Handler.cls
public class ALL_BusinessSites_Handler 
{
    public static void fieldsettingMethod(map<ID, Business_Site__c> oldMap, list<Business_Site__c> newList)
    {       
        set<string> accountNumberSet = new set<string>();
        list<CB_LMA_Relationship__c> toBeInsertedLMArelationships = new list<CB_LMA_Relationship__c>();
        
        if(Trigger.isDelete){ newList = oldMap.Values();}
        
        if(newList != null && !newList.isEmpty())
        {
            for(Business_Site__c bs: newList)
            {
                if(bs.Account_Number__c != null)
                {
                    accountNumberSet.add(bs.Account_Number__c);
                    if(oldMap != null && !oldMap.isEmpty())
                    {
                        accountNumberSet.add(oldMap.get(bs.ID).Account_Number__c);
                    }
                }
            }
        }
        
        map<ID, Account> accountMap;
        
        if(accountNumberSet != null && !accountNumberSet.isEmpty())
        {
            accountMap = new map<ID, Account>([
                Select ID, Name, Account_Number__c
                From Account
                Where Account_Number__c 
                IN :accountNumberSet 
                AND Account_Number__c != null
                AND isDeleted = false
            ]);
        }
        
        map<string, Account> numberToAccount = new map<string, Account>();
        
        system.debug(accountMap);
        
        if(accountMap != null && !accountMap.isEmpty())
        {
            for(Account a: accountMap.values())
            {
                if(a.Account_Number__c != null)
                {
                    numberToAccount.put(a.Account_Number__c, a);
                }
            }
        }
        
        system.debug(numberToAccount);
        
        if(Trigger.isInsert && Trigger.isBefore)
        {        
            for(Business_Site__c bs: newList)
            {
                if(bs.Account_Number__c != null)
                {
                    Account acc = numberToAccount.get(bs.Account_Number__c);
                    system.debug(acc);
                    if(acc != null)
                    {
                        bs.LMA_Account__c = acc.ID;
                        
                        CB_LMA_Relationship__c newCBLMArelation = new CB_LMA_Relationship__c();
                        newCBLMArelation.Dealer_Account__c = bs.Account__c != null ? bs.Account__c : null;
                        newCBLMArelation.LMA_Account__c = acc.ID;
                        toBeInsertedLMArelationships.add(newCBLMArelation);
                    }
                }
            }
            
            if(toBeInsertedLMArelationships != null && !toBeInsertedLMArelationships.isEmpty())
            {
                insert toBeInsertedLMArelationships;
            }
        }
        
        if(Trigger.isUpdate && Trigger.isBefore)
        { 
            Boolean QueryLMArelations = false;
            set<ID> BusinessAccounts = new set<ID>();
            for(Business_Site__c bs: newList)
            {                
                if(bs.Account_Number__c == null || 
                   (bs.Status__c != null && bs.Status__c.toLowerCase() == 'inactive' && bs.Account_Number__c != null))
                {
                    bs.LMA_Account__c = null;
                    QueryLMArelations = true;
                    BusinessAccounts.add(bs.Account__c);
                }                
            }
            
            map<ID, CB_LMA_Relationship__c> LMArelationsMap;
            if(QueryLMArelations)
            {
                LMArelationsMap = new map<ID, CB_LMA_Relationship__c>([
                    Select ID, Name, LMA_Account__c
                    From CB_LMA_Relationship__c
                    Where Dealer_Account__c IN :BusinessAccounts
                ]);
            }
            
            list<CB_LMA_Relationship__c> toBeDeletedRelations = new List<CB_LMA_Relationship__c>();
            if(LMArelationsMap != null && !LMArelationsMap.isEmpty())
            {
                for(CB_LMA_Relationship__c LMArelation: LMArelationsMap.values())
                {
                    for(Business_Site__c bs: newList)
                    {
                        Account acc = numberToAccount.get(oldMap.get(bs.ID).Account_Number__c);
                        
                        if(acc != null && 
                           LMArelation.LMA_Account__c == acc.ID && bs.Status__c != null && bs.Status__c.toLowerCase() != 'inactive')
                        {
                            toBeDeletedRelations.add(LMArelation);
                        }
                    }
                }
            }
            
            if(toBeDeletedRelations != null && !toBeDeletedRelations.isEmpty())
            {
                Delete toBeDeletedRelations; 
            }            
        }
        
        if(Trigger.isDelete)
        {
            list<Business_site__c> oldList = oldMap.values();           
            set<ID> BusinessAccounts = new set<ID>();
            for(Business_Site__c bs: oldMap.values())
            {                
                if(bs.Account_Number__c != null)
                {                    
                    BusinessAccounts.add(bs.Account__c);
                }                
            }
            
            map<ID, CB_LMA_Relationship__c> LMArelationsMap = new map<ID, CB_LMA_Relationship__c>([
                Select ID, Name, LMA_Account__c
                From CB_LMA_Relationship__c
                Where Dealer_Account__c IN :BusinessAccounts
            ]);
            
            
            system.debug(LMArelationsMap);
            
            list<CB_LMA_Relationship__c> toBeDeletedRelations = new List<CB_LMA_Relationship__c>();
            if(LMArelationsMap != null && !LMArelationsMap.isEmpty())
            {
                for(CB_LMA_Relationship__c LMArelation: LMArelationsMap.values())
                {
                    for(Business_Site__c bs: oldMap.values())
                    {
                        Account a = numberToAccount.get(bs.Account_Number__c);
                        if(a != null && 
                           LMArelation.LMA_Account__c == a.ID)
                        {
                            toBeDeletedRelations.add(LMArelation);
                        }
                    }
                }
            }
            
            if(toBeDeletedRelations != null && !toBeDeletedRelations.isEmpty())
            {
                Delete toBeDeletedRelations; 
            } 
        }
    }
}