objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>Digital_Advertising_Strategist__c</fullName>
        <description>This is the Digital Advertising Strategist. The field is filled by a trigger reading the Webid.</description>
        <label>Digital Advertising Strategist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LMA_Analyst__c</fullName>
        <label>LMA Analyst</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>There are two Secondary Owner fields because SEO has a need to have their field hidden to everyone but the SEO profile.</description>
        <inlineHelpText>Secondary Owner. For PowerSEO this is the Content Analyst.</inlineHelpText>
        <label>Secondary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Secondary_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Digital_Advertising_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Advertising Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Marketing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Advertising Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CB_WebID_Handler.cls
public class CB_WebID_Handler 
{
    public static void setAccountPlanFields()
    {
        list<webID__c> webIDlist = Trigger.new != null ? (list<WebID__c>)Trigger.new : null;
        map<ID, WebID__c> webIDMap = Trigger.newMap != null ? (map<ID, WebID__c>)Trigger.newMap : null;
        map<ID, WebID__c> webIDOldMap = Trigger.oldMap != null ? (map<ID, WebID__c>)Trigger.oldMap : new map<ID, WebID__c>();
        set<string> fieldSet = new set<string>{'LMA_Analyst__c', 'LMA_Analyst2__c', 'LMA_strategist__c', 'Digital_Advertising_Strategist__c',
            'Online_Marketing_Specialist__c'};
        set<ID> webIDset = new set<ID>();
        
        if(webIDlist != null && !webIDlist.isEmpty())
        {
            for(WebID__c w: webIDlist)
            {  
                WebID__c newRecord = w;
                WebID__c oldRecord = (webIDOldMap != null && !webIDOldMap.isEmpty()) ? webIDOldMap.get(w.ID) : null;
                
                if(fieldSet != null && newRecord != null && oldRecord != null)
                {
                    boolean fieldValueChanged = false;
                    fieldValueChanged = ALL_UtilitiesLogic.compareNewAndOldTriggerValues(fieldSet, newRecord, oldRecord);
                    
                    if(fieldValueChanged)
                    {
                        webIDset.add(w.ID);
                    }
                }
                
            }
        }
        
        map<ID, Account_Plan__c> accountPlanMap;
        
        if(webIDset != null && !webIDset.isEmpty())
        {
            accountPlanMap = new map<ID, Account_Plan__c>([
                Select Id, WebId__c, OwnerID, Secondary_Owner__c, RecordTypeId
                From Account_Plan__c
                Where WebID__c
                IN :webIDset
            ]);
        }
        
        if(accountPlanMap != null && !accountPlanMap.isEmpty())
        {
            for(Account_Plan__c ap: accountPlanMap.values())
            {
                string recordTypeName;
                if(ap != null && ap.RecordTypeId != null)
                {
                    recordTypeName = ALL_UtilitiesDescribe.getRecordTypeNameOfAnySObject('Account_Plan__c', ap.RecordTypeId);
                }
                
                if(ap.webID__c != null)
                {
                    webID__c currentWebID = webIDMap.get(ap.webId__c);
                    
                    if(currentWebID != null)
                    {
                        if(currentWebID.Digital_Advertising_Strategist__c != null)
                        {
                            if(recordTypeName == 'DAA Account Plan')
                            {
                                if(currentWebID.Digital_Advertising_Strategist__c != null)
                                {
                                    ap.ownerID = currentWebID.Digital_Advertising_Strategist__c;
                                }
                                
                                ap.Secondary_Owner__c = currentWebID.Online_Marketing_Specialist__c;
                            }
                        }
                        if(currentWebID.Digital_Advertising_Strategist__c == null)
                        {
                            if(recordTypeName == 'DAA Account Plan')
                            {
                                if(currentWebID.Online_Marketing_Specialist__c != null)
                                {
                                    ap.ownerID = currentWebID.Online_Marketing_Specialist__c;
                                }
                                ap.Secondary_Owner__c = null;
                            }
                        }
                        if(currentWebID.LMA_Strategist__c != null)
                        {
                            if(recordTypeName == 'AMA Account Plan')
                            {
                                ap.OwnerId = currentWebID.LMA_Strategist__c;
                            }
                        }
                    }
                }
            }
        }
       
        if(accountPlanMap != null && !accountPlanMap.isEmpty())
        {
            update accountPlanMap.values();
            //ALL_UtilitiesData.SerializesObjectList(accountPlanMap.values(), 'Update');           
        }
    }
}