objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Site_Type__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Username</field>
                <operation>notContain</operation>
                <value>integration_user@adp.com</value>
            </filterItems>
            <infoMessage>Select Active Site Type only...</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Type__c</referenceTo>
        <relationshipLabel>Accounts Related to this Site Type</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Site__c.object
<CustomObject>
    <description>Digital list of OEMs belonging to each account.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>LMA Account No</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites</relationshipLabel>
        <relationshipName>Business_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites (LMA Account)</relationshipLabel>
        <relationshipName>Business_Sites1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Business Site</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Business Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Site_Type__c.object
<CustomObject>
    <description>List of possible Site Type attributes for an account</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Site Type</label>
    <nameField>
        <label>Site Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ALL_BusinessSites_Test.cls
@isTest
public class ALL_BusinessSites_Test 
{
    public static testMethod void unitTest()
    {
        Site_Type__c st = DS_TestObjects.NewSiteType();
        st.Name = 'Local Marketing';
        st.Active__c = true;
        insert st;
        
        Account acc = DS_TestObjects.NewAccount();
        acc.Site_Type__c = st.ID;
        acc.Account_Number__c = '12345';
        insert acc;
        
        Business_Site__c bs = new Business_Site__c();
        bs.LMA_Account__c = acc.ID;
        bs.Account_Number__c = acc.Account_Number__c;
        bs.Status__c = 'inactive';
        bs.Account__c = acc.ID;
        insert bs;
        
        bs.Account_Number__c = null;
        update bs;
        
        bs.Account_Number__c = '12345';
        update bs;
        
        delete bs;
    }
}