objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>AA_Account_Plan_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be updated by a stored procedure that looks at related Account Plan records with record type AA Account Plan on the webid.</description>
        <inlineHelpText>This link will open the Advocate’s Account Plan on this webid.</inlineHelpText>
        <label>AA Account Plan Link</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creative_Case_Tally__c</fullName>
        <label>Creative Case Tally</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Creative_Case_Tally__c</fullName>
        <label>Creative Case Tally</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CB_CreativeCaseTallyOnWebIdReset_Batch.cls
global with sharing class CB_CreativeCaseTallyOnWebIdReset_Batch implements Database.Batchable<sObject> {
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        string query = 'SELECT ID, Creative_Case_Tally__c, (Select Id,Creative_Case_Tally__c, RecordType.Name, WebId__c, Status from Cases__r), (Select Id,Creative_Case_Tally__c, RecordType.Name, WebId__c from Account_Plans__r)  from WebID__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<WebID__c> scope){
        list<sObject> webIdCasesAccountPlanList = new list<sObject>();
        for(WebID__c webId: scope)
        {
            if(webId.Creative_Case_Tally__c!=null)
            {
                webId.Creative_Case_Tally__c =0;
                webIdCasesAccountPlanList.add(webId);
            }
            for(Case cs:webId.Cases__r)
            {
                if(cs.RecordType.Name=='Inquiry - Creative'  && cs.Creative_Case_Tally__c!=null){
                   cs.Creative_Case_Tally__c = 0;
                    webIdCasesAccountPlanList.add(cs);
                }
             }
            for(Account_Plan__c acPlan:webId.Account_Plans__r)
            {
                if(acPlan.RecordType.Name == 'DAA Account Plan' && acPlan.Creative_Case_Tally__c!=null){
                    acPlan.Creative_Case_Tally__c = 0;
                    webIdCasesAccountPlanList.add(acPlan);
                }
            }
            
        }
        update webIdCasesAccountPlanList;
    }
    global void finish(Database.BatchableContext BC){
    	
    	Id JobId = null;
    	if(BC != null) { JobId = BC.getJobId(); }
    	
    	AsyncApexJob BatchJob = null;
    	List<AsyncApexJob> BatchJobs = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, CreatedDate 
            FROM AsyncApexJob WHERE Id = :JobId LIMIT 1];
    	
    	ALL_UtilitiesMiscellaneous.Job j = null;
    	if(!BatchJobs.IsEmpty()) { j = new ALL_UtilitiesMiscellaneous.Job(BatchJobs[0]); } 
		else { j = new ALL_UtilitiesMiscellaneous.Job(); }
    	
        ALL_UtilitiesMiscellaneous.SendBatchCompleteMessage(j,
        	'CB_CreativeCaseTallyOnWebIdReset_Batch', 
        	'Finished Resetting the Creative limit to 0 on AccountPlan<-WebID->Cases ', 
        	'Batch Complete');
    }
    
    

}