objects/CMF_Info__c.object
<CustomObject>
    <description>Core BU based identifier numbers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMF Info</relationshipLabel>
        <relationshipName>R00N40000001leBEEAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <label>CMF Info</label>
    <nameField>
        <label>CMF Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMF Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project # [Impact]</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_CMF_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship CMF Info</label>
        <referenceTo>CMF_Info__c</referenceTo>
        <relationshipName>R00N40000001m7zMEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-WEST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go-Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>Dash - Small Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drive - Baseline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lightspeed - Powersports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW - Heavy Equipment</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Rooftops__c</fullName>
        <label>Number of Rooftops</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_User_Connections__c</fullName>
        <label>Number of User Connections</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy / Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Name__c</fullName>
        <label>SubProject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-WEST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>LAO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the LAO Object</description>
        <label>LAO ID</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project (Pilot)</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IMP_UpdateFormsOrder_Test.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   Test Class to test IMP_UpdateFormsOrder_Handler Class and Subproject_On_Laser_Extension Class
Created on:    16 July 2015.
Code Coverage: 100%
------------------------------------------------------------
History
16 July 2015    Vishal Bandari          RQ-04982: Added setupTestData Method
16 July 2015    Vishal Bandari          RQ-04982: Added validateHandlerAndExtension Method
16 July 2015    Vishal Bandari          RQ-04982: Added negitiveTest Method
30 July 2015    Vishal Bandari          RQ-04982: Added code to test Subproject_On_Laser_Extension Class in validateHandlerAndExtension Method
2015-11-04      vishal.bandari@cdk.com  RQ-05690: Added code to test update on Estimated_Install_Date__c field in Laser_Artwork_Order__c
------------------------------------------------------------*/
@IsTest
public class IMP_UpdateFormsOrder_Test
{
    
    //to Setup Test Data
    @testSetup
    public static void setUpTestData()
    {
        //Inserting Sample Project__c
        Project__c projectObj = new Project__c();
        projectObj.Project_Region__c = 'CANADA-EAST';
        insert projectObj;
        
        //Inserting Sample SubProject__c
        Subproject__c subprojectObj = new Subproject__c();
        subprojectObj.SubProject_Name__c = 'Sample Subproject';
        subprojectObj.Project__c = projectObj.Id;
        subprojectObj.SubProject_Region__c = 'CANADA-EAST';
        subprojectObj.Number_of_Rooftops__c = 12.0;
        subprojectObj.Project_Type__c = 'Unhook';
        subprojectObj.Number_of_User_Connections__c = 12.0;
        subprojectObj.Market__c = 'LightSpeed-Powersports';
        subprojectObj.Confidential__c = false;
        subprojectObj.Contract_Roll_Called__c = null;
        insert subprojectObj;
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        insert acc;
        
        CMF_Info__c cmf = new CMF_Info__c();
        cmf.Name = 'Sample CMF';
        cmf.Account__c = acc.Id;
        insert cmf;
        
        List<Laser_Artwork_Order__c> laoList = new List<Laser_Artwork_Order__c>();
        //Inserting Sample Laser_Artwork_Order__c or Forms_Order__c object
        Laser_Artwork_Order__c laoObj = new Laser_artwork_order__C();
        laoObj.Ship_CMF_Info__c = cmf.id;
        laoList.add(laoObj);
        
        //Inserting Sample Laser_Artwork_Order__c or Forms_Order__c object
        Laser_Artwork_Order__c laoObj2 = new Laser_artwork_order__C();
        laoObj.Ship_CMF_Info__c = cmf.id;
        laoList.add(laoObj2);
        
        insert laoList;
        
        //Insert SubProject_External_Reference__c object to relate SubProject and Forms_Order__c
        SubProject_External_Reference__c sperobj = new SubProject_External_Reference__c();
        sperObj.LAO_ID__c = laoObj.id;
        sperObj.Project__c = projectObj.Id;
        sperObj.SubProject__c = subprojectObj.Id;
        insert sperObj;
        
    }
    
    //to Test Confidential__c, Go_Live_Date__c, Project_Manager__c update on Subproject__c reflects on Forms_Order__c and Forms_Collection_c object
    public static testmethod void validateHandlerAndExtension()
    {
        test.startTest(); 
        Subproject__c subprojectObj = [
            SELECT ID, Go_Live_Date__c, Project_Manager__c, Confidential__c, Contract_Roll_Called__c, Impact_Project_Numbers__c,Estimated_Install_Date_EID__c
            FROM Subproject__c
            WHERE SubProject_Name__c = 'Sample Subproject'
        ];
        
        //Initially values are not initialised when Subproject__c is inserted
        System.assertEquals(subprojectObj.Go_Live_Date__c,null, 'Go Live Date got initialized');
        System.assertEquals(subprojectobj.Project_Manager__c,null, 'Project Manager got initialized');
        System.assertEquals(subprojectobj.Confidential__c,false, 'Confidential got changed without update');
        System.assertEquals(subprojectObj.Contract_Roll_Called__c,null, 'Contract Roll Called Date got changed without update');
        System.assertEquals(subprojectObj.Impact_Project_Numbers__c,null, 'Impact Project Numbers got changed without update');
        
        //2015-11-04 vishal.bandari@cdk.com RQ-05690 added code to test update on Estimated_Install_Date__c
        System.assertEquals(subprojectObj.Estimated_Install_Date_EID__c,null, 'Estimated Install Date got changed without update');
        
        //Update the values of Subproject Object field
        subprojectObj.Go_Live_Date__c = System.Date.today();
        subprojectobj.Project_Manager__c = Userinfo.getUserId();
        subprojectobj.Confidential__c = !subprojectobj.Confidential__c;
        subprojectobj.Contract_Roll_Called__c = System.Date.today();
        subprojectobj.Impact_Project_Numbers__c = '5';
        subprojectObj.Estimated_Install_Date_EID__c = Date.Today().addDays(2);
        update subprojectObj;
        
        SubProject_External_Reference__c sperObj = [
            SELECT Id,  LAO_ID__c
            FROM SubProject_External_Reference__c
            WHERE SubProject__c =: subprojectObj.Id
        ];
        
        Laser_Artwork_Order__c laoObj = [
            SELECT ID, Go_Live_Date__c, Project_Manager__c, Confidential__C, Roll_Call_Date__c, Impact_Project_Numbers__c, Estimated_Install_Date__c
            FROM Laser_Artwork_Order__c
            WHERE Id =: sperObj.LAO_ID__c
        ];
        
        //Check for update of Laser_Artwork_Order__c or Forms_Order__c object
        System.assertEquals(subprojectObj.Go_Live_Date__c,laoObj.Go_Live_Date__c, 'Go Live Date not updated in Forms Order');
        System.assertEquals(subprojectObj.Project_Manager__c,laoObj.Project_Manager__c, 'Project Manager not updated in Forms Order');
        System.assertEquals(subprojectobj.Confidential__c,laoObj.Confidential__c, 'Confidential not updated in Forms Order');
        System.assertEquals(subprojectobj.Contract_Roll_Called__c,laoObj.Roll_Call_Date__c, 'Confidential not updated in Forms Order');
        System.assertEquals('5',laoObj.Impact_Project_Numbers__c, 'Impact Project numbers not updated in Forms Order');
        
        //2015-11-04 vishal.bandari@cdk.com RQ-05690 added code to test update on Estimated_Install_Date__c
        System.assertEquals(subprojectObj.Estimated_Install_Date_EID__c,laoObj.Estimated_Install_Date__c, 'Estimated Install Date not updated in Forms Order');
        
        //Testing Standard Layout of Laser_Artwork_Object__c SubprojectInfo Section
        
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(laoObj);
        Subproject_On_Laser_Extension sole = new Subproject_On_Laser_Extension(stdCtrl);
        sole.getRecordDetails();
        System.assertNotEquals(null, sole.sperObj, 'Subproject External Reference Object Not Found');
        
        laoObj = [SELECT ID  FROM Laser_Artwork_Order__c WHERE Id != :sperObj.LAO_ID__c order by CreatedDate desc Limit 1];
        stdCtrl = new ApexPages.StandardController(laoObj);
        sole = new Subproject_On_Laser_Extension(stdCtrl);
        sole.getRecordDetails();
        System.assertEquals(null, sole.sperObj, 'Unexpected value for Subproject External Reference Object');
        test.stopTest();
    }
    
    //to perform negitive test
    public static testmethod void negitiveTest()
    {
        IMP_UpdateFormsOrder_Handler.updateFormOrders(null,null);
    }
}