objects/ConnectedApp_Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>ConnectedApp Sandbox</label>
    <nameField>
        <label>ConnectedApp Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConnectedApp Sandboxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IT_ConnectedAppSandboxHandler.cls
// Author -  Lalitha Adduru
// Description  - Handler class for trigger on ConnectedApp_Sandbox__c object, to encode username and password fields

public class IT_ConnectedAppSandboxHandler {
    public static void encodeDecodeForInsert(List<ConnectedApp_Sandbox__c> TriggerNew)
    {
        if(TriggerNew!=null)
        {            
            for(ConnectedApp_Sandbox__c sandbox : TriggerNew)
            {
                String userName = sandbox.username__c;
                String password = sandbox.password__c;
                Blob blobValue = Blob.valueOf(userName);
                sandbox.username__c=EncodingUtil.base64Encode(blobValue);
                blobValue = Blob.valueOf(password);
                sandbox.password__c=EncodingUtil.base64Encode(blobValue); 
            }            
        }
    }
    public static void encodeDecodeForUpdate(Map<Id,ConnectedApp_Sandbox__c> TriggerOld, List<ConnectedApp_Sandbox__c> TriggerNew)
    {
        for(ConnectedApp_Sandbox__c sandbox : TriggerNew)
        {
            ConnectedApp_Sandbox__c oldsandbox = TriggerOld.get(sandbox.Id);
            system.debug('$$$Old Values - '+'username '+oldsandbox.username__c +' password:'+oldsandbox.password__c);
            system.debug('$$$New Values - '+'username '+sandbox.username__c +' password:'+sandbox.password__c);
            Boolean isEncoded;
            if(oldsandbox.username__c != sandbox.username__c )
            {
                Blob blobValue = Blob.valueOf(sandbox.username__c);
                sandbox.username__c=EncodingUtil.base64Encode(blobValue);
                system.debug('username -- >' + sandbox.username__c);
            }
            if(oldsandbox.password__c != sandbox.password__c)
            {
                Blob blobValue = Blob.valueOf(sandbox.password__c);
                sandbox.password__c=EncodingUtil.base64Encode(blobValue);
                system.debug('Password -- >'+ sandbox.Password__c);
            }       
        }
    }
}