objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HR_Business_Unit__c</fullName>
        <inlineHelpText>Populated via HR DB feed</inlineHelpText>
        <label>HR Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HR_Location__c</fullName>
        <inlineHelpText>Populated via HR DB feed</inlineHelpText>
        <label>HR Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HR_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated via HR DB feed</inlineHelpText>
        <label>HR Manager</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact Manager should be another contact from CDK Global</errorMessage>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>CDK Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HR_Title__c</fullName>
        <inlineHelpText>Populated via HR DB feed</inlineHelpText>
        <label>HR Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <label>Vendor ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EMP_MyInformationController.cls
/*RQ-04089 -line 7 : added fields to query *** Vijay Manimaran *** 2/25/2015 */

public class EMP_MyInformationController {
    public List<User> infoSource { get; set; }
    public list<contact> myInfoContact {get; set; }
    public EMP_MyInformationController() {
        infoSource = [Select Id,Name , (Select FirstName,LastName,Title,Vendor_ID__c,Email,HR_Title__c,HR_Manager__r.Name,HR_Location__c,HR_Business_Unit__c from contacts__r) from User where Id = : UserInfo.getUserId()];
        system.debug('****** infoSource' +infoSource);
        user u =[select id, Name from user where Id = : UserInfo.getUserId() ];
        myInfoContact =[Select FirstName,LastName,Title,Vendor_ID__c,Email,HR_Title__c,HR_Manager__r.Name,HR_Location__c,HR_Business_Unit__c from contact where User__c =: u.id];
    }
}