objects/Employee_Club_Information__c.object
<CustomObject>
    <description>President&apos;s Club criteria for a specific sales rep</description>
    <label>Employee Club Information</label>
    <nameField>
        <displayFormat>ID {00000}</displayFormat>
        <label>Emp Club Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Club Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employee_Information__c.object
<CustomObject>
    <description>User costcenter # as well as Sales Ops Specific attributes</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only Active Users can be linked!</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Employee_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Information</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/President_s_Club_Performance__c.object
<CustomObject>
    <description>Monthly QC plan values for a specific rep/employee</description>
    <fields>
        <fullName>Forecasting_Channel__c</fullName>
        <inlineHelpText>Channel a person&apos;s forecast numbers roll-up to at Kevin Hendrick&apos;s Forecast view</inlineHelpText>
        <label>Forecasting Channel</label>
        <picklist>
            <picklistValues>
                <fullName>ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoffman Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inside Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lightspeed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Inc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSP Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>President&apos;s Club Performance</label>
    <nameField>
        <displayFormat>ID {00000}</displayFormat>
        <label>Pres Club Perform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>President&apos;s Club Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Seasonal_Rate__c.object
<CustomObject>
    <description>Table of rate percentages for QC assignment</description>
    <fields>
        <fullName>April__c</fullName>
        <label>04 April</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>August__c</fullName>
        <label>08 August</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>December__c</fullName>
        <label>12 December</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>February__c</fullName>
        <label>02 February</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>January__c</fullName>
        <label>01 January</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>July__c</fullName>
        <label>07 July</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>June__c</fullName>
        <label>06 June</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>March__c</fullName>
        <label>03 March</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>05 May</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>November__c</fullName>
        <label>11 November</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>October__c</fullName>
        <label>10 October</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>September__c</fullName>
        <label>09 September</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Seasonal Rate</label>
    <nameField>
        <label>Seasonal Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasonal Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DS_SalesPlanManagement_Test.cls
public class DS_SalesPlanManagement_Test
{
    public static testmethod void TestSeasonalRates()
    {
        Seasonal_Rate__c sr1 = new Seasonal_Rate__c();
        sr1.Name = 'Test - Five Ten Ten';
        sr1.January__c = 5;
        sr1.February__c = 10;
        sr1.March__c = 10;
        sr1.April__c = 5;
        sr1.May__c = 10;
        sr1.June__c = 10;
        sr1.July__c = 5;
        sr1.August__c = 10;
        sr1.September__c = 10;
        sr1.October__c = 5;
        sr1.November__c = 10;
        sr1.December__c = 10;
        
        DS_SalesPlanManagement.Result r1 = DS_SalesPlanManagement.SaveSeasonalRate(sr1);
        
        Seasonal_Rate__c sr2 = new Seasonal_Rate__c();
        sr2.Name = 'This name is too long and will cause the upsert to fail, '
            + 'which will then cause the try/catch block to fail and test the catch code.';
        sr2.January__c = 5;
        sr2.February__c = 10;
        sr2.March__c = 10;
        sr2.April__c = 5;
        sr2.May__c = 10;
        sr2.June__c = 10;
        sr2.July__c = 5;
        sr2.August__c = 10;
        sr2.September__c = 10;
        sr2.October__c = 5;
        sr2.November__c = 10;
        sr2.December__c = 10;
        
        DS_SalesPlanManagement.Result r2 = DS_SalesPlanManagement.SaveSeasonalRate(sr2);
        
        List<Seasonal_Rate__c> srs = DS_SalesPlanManagement.GetAllSeasonalRates();
    }
    
    public static testmethod void TestUserPerformances()
    {
        List<String> ForecastingChannels = DS_SalesPlanManagement.GetAllUserForecastingChannels();
        List<String> Titles = DS_SalesPlanManagement.GetAllUserTitles();
        
        User TestUser = DS_TestObjects.NewUser();
        TestUser.Forecasting_Channel__c = (ForecastingChannels!=null?(ForecastingChannels.size()>0?ForecastingChannels[0]:null):null);
        insert TestUser;
        
        List<String> UserIds = new List<String>();
        UserIds.add(TestUser.Id);
        
        // test user methods
        DS_SalesPlanManagement.GetAllForecastingUsers();
        DS_SalesPlanManagement.GetAllActiveForecastingUsers();
        DS_SalesPlanManagement.GetAllInactiveForecastingUsers();
        DS_SalesPlanManagement.GetAllUserManagers();
        
        // successful update
        List<President_s_Club_Performance__c> Performances1 = DS_SalesPlanManagement.GetPCPerformance(UserIds);
        DS_SalesPlanManagement.Result r1 = DS_SalesPlanManagement.SetPCPerformance(Performances1);
        
        // this second update will fail because there is no ID set for the Performance record
        List<President_s_Club_Performance__c> Performances2 = new List<President_s_Club_Performance__c>();
        Performances2.add(new President_s_Club_Performance__c(Forecasting_Channel__c='My fake forecasting channel'));
        DS_SalesPlanManagement.Result r2 = DS_SalesPlanManagement.SetPCPerformance(Performances2);
    }
    
    public static testmethod void TestAssignQC()
    {
        List<String> ForecastingChannels = DS_SalesPlanManagement.GetAllUserForecastingChannels();
        
        User TestUser = DS_TestObjects.NewUser();
        TestUser.Forecasting_Channel__c = (ForecastingChannels!=null?(ForecastingChannels.size()>0?ForecastingChannels[0]:null):null);
        insert TestUser;
        
        Employee_Information__c UserEmployeeInformation = new Employee_Information__c(User__c=TestUser.Id,Name='Test Employee Information');
        insert UserEmployeeInformation;
        
        DS_SalesPlanManagement.UserWithCredit uwqc = new DS_SalesPlanManagement.UserWithCredit();
        uwqc.EmployeeInformationId = UserEmployeeInformation.Id;
        uwqc.ClubInformations = new List<Employee_Club_Information__c>();
        uwqc.Performances = new List<President_s_Club_Performance__c>();
        uwqc.UserId = TestUser.Id;
        uwqc.ForecastingChannel = TestUser.Forecasting_Channel__c;
        uwqc.TotalQC = '100000';
        uwqc.PCNumber = '105000';
        uwqc.Updated = false;
        uwqc.Message = 'Error';
        
        List<DS_SalesPlanManagement.UserWithCredit> uwqcs = new List<DS_SalesPlanManagement.UserWithCredit>();
        uwqcs.add(uwqc);
        
        Seasonal_Rate__c sr1 = new Seasonal_Rate__c();
        sr1.Name = 'Test - Five Ten Ten';
        sr1.January__c = 5;
        sr1.February__c = 10;
        sr1.March__c = 10;
        sr1.April__c = 5;
        sr1.May__c = 10;
        sr1.June__c = 10;
        sr1.July__c = 5;
        sr1.August__c = 10;
        sr1.September__c = 10;
        sr1.October__c = 5;
        sr1.November__c = 10;
        sr1.December__c = 10;
        DS_SalesPlanManagement.Result r1 = DS_SalesPlanManagement.SaveSeasonalRate(sr1);
        
        List<Seasonal_Rate__c> srs = DS_SalesPlanManagement.GetAllSeasonalRates();
        Seasonal_Rate__c sr2 = (srs!=null?(srs.size()>0?srs[0]:null):null);
        
        List<String> years = DS_SalesPlanManagement.getYears();
        String year = (years!=null?(years.size()>0?years[0]:null):null);
        
        // failure cases
        DS_SalesPlanManagement.Result r2 = DS_SalesPlanManagement.Assign('QC',null,sr2.Id,year);
        DS_SalesPlanManagement.Result r3 = DS_SalesPlanManagement.Assign('QC',new List<DS_SalesPlanManagement.UserWithCredit>(),sr2.Id,year);
        DS_SalesPlanManagement.Result r4 = DS_SalesPlanManagement.Assign('QC',uwqcs,null,year);
        DS_SalesPlanManagement.Result r5 = DS_SalesPlanManagement.Assign('QC',uwqcs,sr2.Id,null);
        DS_SalesPlanManagement.Result r6 = DS_SalesPlanManagement.Assign('QC',uwqcs,'123000000abc456',year);
        
        // success case
        DS_SalesPlanManagement.Result r7 = DS_SalesPlanManagement.Assign('QC',uwqcs,sr2.Id,year);
        
        // 1 more error cases
        DS_SalesPlanManagement.Result r8 = DS_SalesPlanManagement.Assign('QC',uwqcs,sr2.Id,year); // duplicate id error
        
        // 1 more success case
        uwqcs[0].ClubInformations = null;
        uwqcs[0].Performances = null;
        DS_SalesPlanManagement.Result r9 = DS_SalesPlanManagement.Assign('QC',uwqcs,sr2.Id,year); // updating pre-existing values from successful insert
    }
}