objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>By_Pass_Forms_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>By Pass Forms Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Call_Date__c</fullName>
        <label>Roll Call Date</label>
        <type>Date</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date_EID__c</fullName>
        <label>Estimated Install Date (EID)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go-Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>LAO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the LAO Object</description>
        <label>LAO ID</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <recordTypes>
        <fullName>FO</fullName>
        <active>true</active>
        <description>Laser Artwork Order</description>
        <label>FO</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IMP_UpdateFormsOrder_Handler.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   To Update Forms_Order__c and Forms_Collection__c objects when Subproject__c is Updated
Test Class:    IMP_UpdateFormsOrder_Test
Created on:    15 July 2015.
Code Coverage: 100%
------------------------------------------------------------
History
15 July 2015    Vishal Bandari        -  RQ-04982: Added updateFormOrders method
28 July 2015    Siva.Pragada@cdk.com  -  added boolean check to see if the soql query is necessary. 
                                         we need to query only when the field values change. 
28 July 2015    Siva.Pragada@cdk.com  -  separeated the update dml into separate transaction using future update method in Utilities class.
                                         When we have cross object updates 
									     this would cause Recursive trigger error. We have cross object updates on FO to Task and Task to FO. 
28 July 2015    vishal.bandari@cdk.com - changed the update method to synchronous from future method
2015-11-04      vishal.bandari@cdk.com - RQ-05690: Added code to update Estimated_Install_Date__c field in Laser_Artwork_Order__c
------------------------------------------------------------*/
public class IMP_UpdateFormsOrder_Handler 
{
    public static void updateFormOrders(Map<Id,SubProject__c> newMap, Map<Id,SubProject__c> oldMap)
    {
        try
        {
            Boolean fieldValuesChanged = false;
            
            for(SubProject__c newSub: newMap.values())
            {
                SubProject__c oldSub = oldMap.get(newSub.ID);
                
                if(newSub.Go_Live_Date__c != oldSub.Go_Live_Date__c  || 
                   newSub.Project_Manager__c!= oldSub.Project_Manager__c ||  
                   newSub.Confidential__c!= oldSub.Confidential__c ||
                   newSub.Contract_Roll_Called__c != oldSub.Contract_Roll_Called__c ||
                   newSub.Impact_Project_Numbers__c != oldSub.Impact_Project_Numbers__c || 
                   newSub.Estimated_Install_Date_EID__c != oldSub.Estimated_Install_Date_EID__c)
                {
                    fieldValuesChanged = true; 
                    break;
                } 
            }
            // added boolean check to see if the soql query is necessary. we need to query only when the field values change. 
            // 2015-07-28 - Siva.Pragada@cdk.com
            if(fieldValuesChanged) 
            {
                Map<id,SubProject_External_Reference__c> sperMap = new Map<id,SubProject_External_Reference__c>([
                        SELECT Id, LAO_ID__c, SubProject__c,SubProject__r.Impact_Project_Numbers__c,
                               SubProject__r.Contract_Roll_Called__c, SubProject__r.Project_Manager__c, SubProject__r.Confidential__c, 
                               SubProject__r.Estimated_Install_Date_EID__c 
                        FROM SubProject_External_Reference__c
                        WHERE SubProject__c IN: newMap.keySet() 
                        AND LAO_ID__c != null
                    ]);
                
                List<Id> requiredFormsOrderIds = new List<Id>();
                
                for(SubProject_External_Reference__c sperObj: sperMap.values())
                {
                    requiredFormsOrderIds.add(sperObj.LAO_ID__c);
                }
                
                Map<Id,Laser_Artwork_Order__c> formsOrderMap = new Map<Id,Laser_Artwork_Order__c>([
                        SELECT Id, By_Pass_Forms_Validation_Rules__c, Confidential__c,Go_Live_Date__c,
                               Project_Manager__c, Roll_Call_Date__c, Impact_Project_Numbers__c, Estimated_Install_Date__c
                        FROM Laser_Artwork_Order__c
                        WHERE Id In: requiredFormsOrderIds
                    ]);
                
                Set<Laser_Artwork_Order__c> formsOrderSet = new Set<Laser_Artwork_Order__c>();
                
                for(SubProject_External_Reference__c sperObj : sperMap.values())
                {
                    SubProject__c newObj = newMap.get(sperObj.SubProject__c);
                    SubProject__c oldObj = oldMap.get(sperObj.SubProject__c);
                    Laser_Artwork_Order__c laoObj = formsOrderMap.get(sperObj.LAO_ID__c);
                    laoObj.By_Pass_Forms_Validation_Rules__c = !laoObj.By_Pass_Forms_Validation_Rules__c;
                    laoObj.Confidential__c = sperObj.SubProject__r.Confidential__c;
                    laoObj.Go_Live_Date__c = newObj.Go_Live_Date__c;
                    laoObj.Project_Manager__c = sperObj.SubProject__r.Project_Manager__c;
                    laoObj.Roll_Call_Date__c = sperObj.SubProject__r.Contract_Roll_Called__c;
                    laoObj.Impact_Project_Numbers__c = sperObj.SubProject__r.Impact_Project_Numbers__c;
                    
                    //2015-11-04 vishal.bandari@cdk.com RQ-05690 added code to update on Estimated_Install_Date__c
                    laoObj.Estimated_Install_Date__c = sperObj.SubProject__r.Estimated_Install_Date_EID__c;
                    
                    if(!formsOrderSet.contains(laoObj))
                    {
                        formsOrderSet.add(laoObj);
                    }
                }
                //Utilities.SerializesObjectList(new List<sobject>(formsOrderSet), 'Update');
                update new List<Laser_Artwork_Order__c>(formsOrderSet);
            }
        }
        catch(Exception e)
        {
            System.debug('Exception: '+e.getMessage()+' At '+e.getLineNumber());
        }
    }
}