objects/Request__c.object
<CustomObject>
    <description>Used by SF Admins to send configuration updates to Sales Automation</description>
    <fields>
        <fullName>Business_Justification__c</fullName>
        <inlineHelpText>The business reasons for the requested change.</inlineHelpText>
        <label>Business Justification</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Change_Classification__c</fullName>
        <inlineHelpText>Routine: standard procedural change 
Bug: Issue with SF 
Emergency: Issue preventing users from completing work 
Minor/Major Release: 
Training Opp: User error that can be fixed with training</inlineHelpText>
        <label>Change Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Routine</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Minor Release (&gt;16)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Release (&gt;40)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mondo (&gt;100)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Completed_in_Prod__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>From QA to Production</inlineHelpText>
        <label>Completed in Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed_in_QA__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>From Unified to QA</inlineHelpText>
        <label>Completed in QA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed_in_Unified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>From Dev to Unified</inlineHelpText>
        <label>Completed in Unified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deployment_Strategy__c</fullName>
        <label>Deployment Strategy</label>
        <picklist>
            <picklistValues>
                <fullName>Add to ALL ENVIRONMENTS, no review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In TRAINING for Review Then PROD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migrate from FULLDEV to TRAINING Then PROD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In PROD Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FULLDEV2 Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In TRAINING Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In QA only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In UNIFIED only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migrate from ORIGINAL ENVIRONMENT to UNIFIED to QA to PROD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_to_Completion__c</fullName>
        <inlineHelpText>Please fill in time it took to completion in partial or full hours (eq. 0.25, 0.5, 2, 6)</inlineHelpText>
        <label>Duration to Completion</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Estimate__c</fullName>
        <inlineHelpText>Initial estimate in hours. Visible to Administrators only.</inlineHelpText>
        <label>Initial Estimate</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Internal_Priority__c</fullName>
        <label>Internal Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1 Immediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 To Be Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Wishlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending BU for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - In Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - Under Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Pre-Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification - Unassigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Groups_Impacted__c</fullName>
        <label>User Groups Impacted</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - Enterprise Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - IFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - BDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - CrdtSvcs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Data Librarians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Inside Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Laser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - PSG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS - Traver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGT - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGT - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MV - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVR - Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVR - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVR - Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Request_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Team Members</relationshipLabel>
        <relationshipName>Request_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF Config Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF Developer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Request_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Team Member</label>
    <nameField>
        <displayFormat>RTM-{0000}</displayFormat>
        <label>Request Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/All_RequestHandler_Test.cls
// Author : Lalitha Adduru
// Description : Test class for All_Request trigger
// History : Modified by Lalitha Adduru on 9 October 2015 to satisfy validation rules on request object

@isTest
public class All_RequestHandler_Test {
    public static testmethod void testRequestTrigger()
    {
        Request__c req = new Request__c(
            Name = 'TestDescription',
            Details__c='TestDetails',
            Business_Justification__c = 'TestJustification',
            Deployment_Strategy__c='In PROD Only',
            Status__c='Open',
            Internal_Priority__c='2 High', 
            Initial_Estimate__C= 12345,
            User_Groups_Impacted__c='CB - Finance',
            Duration_to_Completion__c = 20
        );
        insert req;
        
        User testUserOne = DS_TestObjects.NewAdminUser();
        insert testUserOne;
        Request_Team_Member__c test_rtm = new Request_Team_Member__c(Request__c = req.id, User__c= testUserOne.id, Role__c='SF Config Admin');
        insert test_rtm;        
        EntitySubscription follower = new EntitySubscription(ParentId = req.id , subscriberId = UserInfo.getUserId());
        insert follower;
        req.Name = 'TestDesriptionEdited';
        update req;
        req.Status__c = 'Completed';
        req.Change_Classification__c = 'Routine';
        req.Duration_to_Completion__c = 20;
        req.Completed_in_Unified__c = true;
        req.Completed_in_Prod__c= true;
        req.Completed_in_QA__c = true;
        update req;       
    }
}