objects/Request__c.object
<CustomObject>
    <description>Used by SF Admins to send configuration updates to Sales Automation</description>
    <fields>
        <fullName>Assigned_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Config</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>startsWith</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Classification__c</fullName>
        <inlineHelpText>Routine: standard procedural change 
Bug: Issue with SF 
Emergency: Issue preventing users from completing work 
Minor/Major Release: 
Training Opp: User error that can be fixed with training</inlineHelpText>
        <label>Change Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Routine</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Minor Release (&gt;16)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Release (&gt;40)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mondo (&gt;100)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration_to_Completion__c</fullName>
        <inlineHelpText>Please fill in time it took to completion in partial or full hours (eq. 0.25, 0.5, 2, 6)</inlineHelpText>
        <label>Duration to Completion</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Estimate__c</fullName>
        <inlineHelpText>Initial estimate in hours. Visible to Administrators only.</inlineHelpText>
        <label>Initial Estimate</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_Not_Completed_In_All_Environments__c</fullName>
        <label>Reason Not Completed In All Environments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending BU for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - In Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - Under Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Pre-Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification - Unassigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Request_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Team Members</relationshipLabel>
        <relationshipName>Request_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF Config Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF Developer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Request_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Team Member</label>
    <nameField>
        <displayFormat>RTM-{0000}</displayFormat>
        <label>Request Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DS_RequestAssignOnCloseTest.cls
//RQ-05454 Hemanth.kesapragada@cdk.com Change status from closed to completed,Modified Test Class
@IsTest
public class DS_RequestAssignOnCloseTest
{
        
    //Toggle enable/disable debug logs
    private static final boolean GENERATE_DEBUG_LOGS = true;
    //TestMethod control variables
    private static final boolean RUN_ALL = true;
    private static final boolean RUN_TEST_REQUEST = true;

    @TestSetup
    public static void loadData()
    {
        User userObj = DS_TestObjects.NewAdminUser();
        userObj.UserRoleId = [Select Id, RollupDescription From UserRole Where RollupDescription like '%System Administrator%'].Id;
        insert userObj;
        
        System.runAs(DS_TestObjects.CurrentUser()) 
        {
            test.startTest();
            Request__c requestObj = new Request__c();
            requestObj.Name = 'TestRequest';
            requestObj.ownerid=userObj.Id;
            requestObj.Initial_Estimate__c = 5;
            insert requestObj;
            test.stopTest();
        }
    }
    
    public static testmethod void TestRequest()
    {
        if(RUN_ALL || RUN_TEST_REQUEST)
           {
               User userObj = [select id from user order by lastmodifiedDate desc limit 1];
               System.runAs(DS_TestObjects.CurrentUser()) 
               {
                   Test.startTest();
                   Request__c reqObj = [
                       select id,Status__c,
                       Reason_Not_Completed_In_All_Environments__c,
                       Change_Classification__c,Duration_to_Completion__c,
                       Assigned_Config__c,ownerid,createdById
                       from Request__c 
                   ];
                   System.assertNotEquals(reqObj.OwnerId,reqObj.CreatedById);
                   if(reqObj != null) {
                       reqObj.Status__c = 'Completed'; 
                       reqObj.Reason_Not_Completed_In_All_Environments__c = 'Testing...';
                       reqObj.Change_Classification__c = 'Routine';
                       reqObj.Duration_to_Completion__c = 25;
                       reqObj.Assigned_Config__c = userObj.Id;
                       reqObj.Initial_Estimate__c = 5;
                       
                       Request_Team_Member__c rtm = new Request_Team_Member__c();
                       rtm.Request__c = reqObj.Id;
                       rtm.Role__c = 'SF Config Admin';
                       rtm.User__c = UserInfo.getUserId();
                       insert rtm;
                       
                       update reqObj;
                   }
                   Test.stopTest();
                   reqObj = [
                       select id,ownerid,createdById
                       from Request__c 
                       where id=:reqObj.Id
                   ];
                   System.assertEquals(reqObj.OwnerId,reqObj.CreatedById);
               } 
           }
           
    }
    
    private static void setHeaderLogs(String txt)
    {
        if(GENERATE_DEBUG_LOGS)
        {
            //Genereate debug logs
            System.debug('**********************************');
            System.debug('***** '+txt);
            System.debug('**********************************');  
        }
        
    }
}